[package]
name = "signalspec"
version = "0.1.0"
authors = [ "km@kevinmehall.net" ]
edition = "2018"

[workspace]
members = ["cli", "plugins/starfish", "plugins/vcd"]

[dependencies]
log = "0.3.2"
bit-set = "0.4.0"
num-complex = "0.1.35"
byteorder = "1.0.0"
peg = "0.6"
vec_map = "0.8.0"
scoped-pool = "1.0"

[dev-dependencies]
env_logger = "0.3"

[[test]]
name = "check"
harness = false
