[package]
name = "signalspec"
version = "0.1.0"
authors = [ "km@kevinmehall.net" ]

[workspace]
members = ["cli", "plugins/starfish", "plugins/vcd"]

[dependencies.peg]
git = "https://github.com/kevinmehall/rust-peg.git"

[dependencies]
log = "0.3.2"
typed-arena = "1.0.1"
bit-set = "0.2.0"
vec_map = "0.3.0"
lazy_static = "0.1.*"
ref_slice = "0.1.*"

[[test]]
name = "check"
harness = false
