[package]
name = "signalspec_cli"
version = "0.1.0"
authors = [ "km@kevinmehall.net" ]
edition = "2018"

[dependencies]
signalspec = { path = "../" }
log = "0.4.14"
env_logger = "0.10.0"
argparse = "0.2.1"
codespan-reporting = "0.11.1"

[[bin]]
name = "signalspec"
path = "main.rs"
