[package]
name = "signalspec-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.6"
lsp-server = "0.6.0"
lsp-types = "0.93.1"
serde_json = "1.0.85"
signalspec = { path = "../" }

[[bin]]
name = "signalspec-lsp"
path = "main.rs"
